name: Lint

on: [push]

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # ESLint and Prettier must be in `package.json`
      - name: Install modules
        run: yarn
      - name: Initalizing eslint
        run: ./node_modules/.bin/eslint --init

      - name: Run ESLint
        run: yarn run eslint . --ext .js,.jsx,.ts,.tsx

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          eslint: true
